swagger: "2.0"
info:
  title: mobile API
  description: mobile has every tool to get any job done, so codename for the new
    mobile APIs.
  version: 1.0.0
  contact:
    email: astaxie@gmail.com
basePath: /v1
paths:
  /customer/backlogin/judge:
    post:
      tags:
      - customer
definitions:
  float:
    title: float
    type: object
  models.ZDTCustomer.Customer:
    title: Customer
    type: object
  models.ZDTProduct.ProductList:
    title: ProductList
    type: object
